# Translations template for PROJECT.
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2019.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2019-11-27 19:51+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.7.0\n"

msgid "Python Errors"
msgstr "Python Errors"

msgid "PYTHONPATH"
msgstr "PYTHONPATH"

msgid "Blender will fail to load if the ``PYTHONPATH`` is set incorrectly."
msgstr "Blender will fail to load if the ``PYTHONPATH`` is set incorrectly."

msgid "This can be useful for Python developers who want to use their own Python installation however, it will prevent Blender from opening at all when set to an incompatible version of Python."
msgstr "This can be useful for Python developers who want to use their own Python installation however, it will prevent Blender from opening at all when set to an incompatible version of Python."

msgid "To see if this is the cause of an error temporary unset the environment variable and reload Blender."
msgstr "To see if this is the cause of an error temporary unset the environment variable and reload Blender."

msgid "See `Python's documentation <https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH>`__ for details."
msgstr "See `Python's documentation <https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH>`__ for details."

msgid "Precompiled Libraries"
msgstr "Precompiled Libraries"

msgid "While not common practice, Python add-ons can be distributed with their own precompiled libraries. Unlike regular Python scripts, these are not portable between different platforms."
msgstr "While not common practice, Python add-ons can be distributed with their own precompiled libraries. Unlike regular Python scripts, these are not portable between different platforms."

msgid "It is possible the library is incompatible with your Blender installation (attempting to load a library built for a different version of Python, or loading a 32-bit library on a 64-bit system)."
msgstr "It is possible the library is incompatible with your Blender installation (attempting to load a library built for a different version of Python, or loading a 32-bit library on a 64-bit system)."

msgid "If the add-on contains ``.pyd`` or ``.so`` files, check that the distribution is compatible with your operating system."
msgstr "If the add-on contains ``.pyd`` or ``.so`` files, check that the distribution is compatible with your operating system."

msgid "Platform Specific"
msgstr "Platform Specific"

# Windows
msgid "Windows"
msgstr "Cửa Sổ"

# Mixed Python Libraries (DLL's)
msgid "Mixed Python Libraries (DLL's)"
msgstr "-- Mixed Python Libraries (DLL's)"

msgid "If Python is raising errors or you have an add-on that just fails when enabled with an error, e.g: ``... is not a valid Win32 application.``."
msgstr "If Python is raising errors or you have an add-on that just fails when enabled with an error, e.g: ``... is not a valid Win32 application.``."

msgid "A Python traceback."
msgstr "A Python traceback."

msgid "This may be caused by some inconsistency in the Python libraries. While Blender comes with its own bundled Python interpreter, duplicate, incompatible libraries can cause problems."
msgstr "This may be caused by some inconsistency in the Python libraries. While Blender comes with its own bundled Python interpreter, duplicate, incompatible libraries can cause problems."

msgid "To find out which Python Library caused the Problem check the error message."
msgstr "To find out which Python Library caused the Problem check the error message."

msgid "This is normally reported somewhere around the bottom line of the traceback. With the error above you see the problem is caused while trying to import ``_socket``. This corresponds to either a file named ``_socket.py`` or ``_socket.pyd``."
msgstr "This is normally reported somewhere around the bottom line of the traceback. With the error above you see the problem is caused while trying to import ``_socket``. This corresponds to either a file named ``_socket.py`` or ``_socket.pyd``."

# To help troubleshoot this problem, the following script can be pasted into the Text editor and run to check for duplicate libraries in your search path. (The output will show in :doc:`Command Line Window </advanced/command_line/introduction>`.)
msgid "To help troubleshoot this problem, the following script can be pasted into the Text editor and run to check for duplicate libraries in your search path. (The output will show in :doc:`Command Line Window </advanced/command_line/introduction>`.)"
msgstr "To help troubleshoot this problem, the following script can be pasted into the Text editor and run to check for duplicate libraries in your search path. (output will show in :doc:`Command Line Window </advanced/command_line/introduction>`)."

